fastparcel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from core import views
from core.customer import views as customer_views 
from core.courier import views as courier_views 
from core.courier import views as courier_views ,apis as courier_apis
from django.conf import  settings
from django.conf.urls.static import static

 
customer_urlpatterns = [
    path('',customer_views.home,name="home"),
    path('profile/',customer_views.profile_page,name="profile"),
    path('payment_method/',customer_views.payment_method_page,name="payment_method"),
    path('create_job/',customer_views.create_job_page,name="create_job"),

    path('jobs/current/',customer_views.current_jobs_page,name="current_jobs"),
    path('jobs/archived/',customer_views.archived_jobs_page,name="archived_jobs"),
    path('jobs/<job_id>/',customer_views.job_page,name="job")
    
 ]
courier_urlpatterns = [
    path('',courier_views.home,name="home"),
    path('jobs/available/',courier_views.available_jobs_page,name="available_jobs"),
    path('jobs/available/<id>/',courier_views.available_job_page,name="available_job"),
    path('jobs/current/',courier_views.current_job_page,name="current_job"),
    path('jobs/current/<id>/take_photo/',courier_views.current_job_take_photo_page,name="current_job_take_photo"),

    path('api/jobs/available/',courier_apis.available_jobs_api,name="available_jobs_api"),
    path('api/jobs/current/<id>/update/',courier_apis.current_job_update_api,name="current_job_update_api"),



]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('', include('social_django.urls', namespace='social')),
    path('sign-in/',auth_views.LoginView.as_view(template_name="sign_in.html")),
    path('sign-out/',auth_views.LogoutView.as_view(next_page="/")),
    path('sign-up/',views.sign_up),
    path('customer/',include((customer_urlpatterns,'customer'))),
    path('courier/',include((courier_urlpatterns,'courier'))),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE) 
    avatar=models.ImageField(upload_to='customer/avatars/',blank=True,null=True)
    phone_number=models.CharField(max_length=50,blank=True)
    stripe_customer_id=models.CharField(max_length=255,blank=True)
    stripe_payment_method_id=models.CharField(max_length=255,blank=True)
    stripe_card_last4=models.CharField(max_length=255,blank=True)


    def __str__(self):
      return self.user.get_full_name()

class Courier(models.Model):
      user=models.OneToOneField(User,on_delete=models.CASCADE) 
      lat=models.FloatField(default=0)
      lng=models.FloatField(default=0)
      def __str__(self):
         return self.user.get_full_name()

class Category(models.Model):
  slug=models.CharField(max_length=255,unique=True)
  name=models.CharField(max_length=255)
  def __str__(self):
      return self.name

class Job(models.Model):
  SMALL_SIZE= "small"
  MEDIUM_SIZE= "medium"
  LARGE_SIZE= "large"
  SIZES = (
    (SMALL_SIZE, 'Small'),
    (MEDIUM_SIZE, 'Medium'),
    (LARGE_SIZE, 'Large'),
  )

  CREATING_STATUS = "creating"
  PROCESSING_STATUS = "processing"
  PICKING_STATUS = "picking"
  DELIVERING_STATUS = "delivering"
  COMPLETED_STATUS = "completed"
  CANCELED_STATUS = "canceled"
  STATUSES = (
    (CREATING_STATUS, 'Creating'),
    (PROCESSING_STATUS, 'Processing'),
    (PICKING_STATUS, 'Picking'),
    (DELIVERING_STATUS, 'Delivering'),
    (COMPLETED_STATUS, 'Completed'),
    (CANCELED_STATUS, 'Canceled'),
  )
#step1
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
  courier = models.ForeignKey(Courier, on_delete=models.CASCADE,null=True,blank=True)

  name = models.CharField(max_length=255)
  description = models.CharField(max_length=255)
  category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
  size = models.CharField(max_length=20, choices=SIZES, default=MEDIUM_SIZE)
  quantity = models.IntegerField(default=1)
  photo = models.ImageField(upload_to='job/photos/')

  status = models.CharField(max_length=20, choices=STATUSES, default=CREATING_STATUS)
  created_at = models.DateTimeField(default=timezone.now)
#step2
  pickup_address=models.CharField(max_length=255,blank=True)
  pickup_lat=models.FloatField(default=0)
  pickup_lng=models.FloatField(default=0)
  pickup_name=models.CharField(max_length=255,blank=True)
  pickup_phone=models.CharField(max_length=50,blank=True)


  delivery_address=models.CharField(max_length=255,blank=True)
  delivery_lat=models.FloatField(default=0)
  delivery_lng=models.FloatField(default=0)
  delivery_name=models.CharField(max_length=255,blank=True)
  delivery_phone=models.CharField(max_length=50,blank=True)

  duration=models.IntegerField(default=0)
  distance=models.FloatField(default=0)
  price=models.FloatField(default=0)

  pickup_photo=models.ImageField(upload_to='job/pickup_photos/',null=True,blank=True)
  pickedup_at=models.DateField(null=True,blank=True)

  delivery_photo=models.ImageField(upload_to='job/delivery_photos/',null=True,blank=True)
  delivered_at=models.DateField(null=True,blank=True)
  


def __str__(self):
    return self.name

class Transaction(models.Model):
  stripe_payment_intent_id=models.CharField(max_length=255,unique=True)
  job=models.ForeignKey(Job,on_delete=models.CASCADE)
  amount=models.FloatField(default=0)
  created_at=models.DateTimeField(default=timezone.now)
def __str__(self):
    return self.stripe_payment_intent_id

core/courier/views.py
from django.shortcuts import  redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import settings
from core.models import *
@login_required
def home(request):
    return redirect(reverse('courier:available_jobs'))

@login_required(login_url="/sign-in/?next=/courier/")
def available_jobs_page(request):
    return render(request,'courier/available_jobs.html',{
        "GOOGLE_MAP_API_KEY":settings.GOOGLE_MAP_API_KEY

    })
@login_required(login_url="/sign-in/?next=/courier/")
def available_job_page(request,id):
    job=Job.objects.filter(id=id,status=Job.PROCESSING_STATUS).last()
    
    if not job:
        return redirect(reverse('courier:available_jobs'))

    if request.method =='POST':
        job.courier=request.user.courier
        job.status=Job.PICKING_STATUS
        job.save()

        return redirect(reverse('courier:available_jobs'))
    return render(request,'courier/available_job.html',{
        "job":job
    })
@login_required(login_url="/sign-in/?next=/courier/")
def current_job_page(request):
    job=Job.objects.filter(
        courier=request.user.courier,
        status__in=[
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).last()
    return render(request,'courier/current_job.html',{
        "job":job,
        "GOOGLE_MAP_API_KEY": settings.GOOGLE_MAP_API_KEY
    })
@login_required(login_url="/sign-in/?next=/courier/")
def current_job_take_photo_page(request,id):
    job=Job.objects.filter(
        id=id,
        courier=request.user.courier,
        status__in=[
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).last()

    if not job:
        return redirect(reverse('courier:current_job'))
    return render(request,'courier/current_job_take_photo.html',{
        "job":job
    })

core/customer/views.py
import requests
import stripe
import firebase_admin
from firebase_admin import credentials,auth
from django.shortcuts import  render,redirect
from django.contrib.auth.decorators import login_required
from stripe.api_resources import customer
from core.customer import forms
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.conf import settings
from core.models import *


cred = credentials.Certificate(settings.FIREBASE_ADMIN_CREDENTIAL)
firebase_admin.initialize_app(cred)
stripe.api_key=settings.STRIPE_API_SECRET_KEY

@login_required()
def home(request):
    return redirect(reverse('customer:profile'))
@login_required(login_url="/sign-in/?next=/customer/")
def profile_page(request):
    user_form=forms.BasicUserForm(instance=request.user)
    customer_form=forms.BasicCustomerForm(request.POST,instance=request.user.customer)
    password_form=PasswordChangeForm(request.user)

    if request.method=="POST":

     if request.POST.get('action') == "upadte_profile":
        user_form=forms.BasicUserForm(request.POST,instance=request.user)
        customer_form=forms.BasicCustomerForm(request.POST,request.FILES,instance=request.user.customer) 
        if user_form.is_valid() and customer_form.is_valid:
            user_form.save()
            customer_form.save()
            messages.success(request,'Your Profile has been updated')
            return redirect(reverse('customer:profile'))
        elif  request.POST.get('action') == "upadte_password":
            password_form=PasswordChangeForm(request.user,request.POST)
            if password_form.is_valid():
             user=password_form.save()
            update_session_auth_hash(request,user)


            messages.success(request,'Your Password has been updated')
            return redirect(reverse('customer:profile'))
        elif  request.POST.get('action') == "upadte_phone":
             firebase_user=auth.verify_id_token(request.POST.get('id_token'))
             request.user.customer.phone_number=firebase_user['phone_number']
             request.user.customer.save()
             return redirect(reverse('customer:profile'))



    return render(request,'customer/profile.html', {
        "user_form": user_form,
        "customer_form": customer_form,
        "password_form": password_form
    })
   


@login_required(login_url="/sign-in/?next=/customer/")
def payment_method_page(request):
    current_customer=request.user.customer
    if request.method == "POST":
        stripe.PaymentMethod.detach(current_customer.stripe_payment_method_id)
        current_customer.stripe_payment_method_id=" "
        current_customer.stripe_card_last4=" "
        current_customer.save()
        return redirect(reverse('customer:payment_method'))

    if not current_customer.stripe_customer_id:
        customer=stripe.Customer.create()
        current_customer.stripe_customer_id=customer['id']
        current_customer.save()

    stripe_payment_methods=stripe.PaymentMethod.list(
        customer=current_customer.stripe_customer_id,
        type="card",

    )
    print(stripe_payment_methods) 

    if stripe_payment_methods and len(stripe_payment_methods.data) > 0:
        payment_method=stripe_payment_methods.data[0]
        current_customer.stripe_payment_method_id=payment_method.id
        current_customer.stripe_card_last4=payment_method.card.last4
        current_customer.save()
    else:
        current_customer.stripe_payment_method_id=" "
        current_customer.stripe_card_last4=" "
        current_customer.save()
    
    if not current_customer.stripe_payment_method_id:
      intent =stripe.SetupIntent.create(
          customer=current_customer.stripe_customer_id

    )

      return render(request,'customer/payment_method.html',{
        "client_secret":intent.client_secret,
        "STRIPE_API_PUBLIC_KEY":settings.STRIPE_API_PUBLIC_KEY,
    })
    else:
        return render(request,'customer/payment_method.html')


@login_required(login_url="/sign-in/?next=/customer/")
def create_job_page(request):
    current_customer=request.user.customer
    if not current_customer.stripe_payment_method_id:
        return redirect(reverse('customer:payment_method'))
    has_current_job=Job.objects.filter(
        customer=current_customer,
        status__in=[
            Job.PROCESSING_STATUS,
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).exists()
    if has_current_job:
        messages.warning(request,"You currently have a processing job")
        return redirect(reverse('customer:current_jobs'))
    creating_job=Job.objects.filter(customer=current_customer,status=Job.CREATING_STATUS).last()
    step1_form=forms.JobCreateStep1Form(instance=creating_job)
    step2_form=forms.JobCreateStep2Form(instance=creating_job)
    step3_form=forms.JobCreateStep3Form(instance=creating_job)



    if request.method=="POST":
        if request.POST.get('step')=='1':
            step1_form=forms.JobCreateStep1Form(request.POST,request.FILES,instance=creating_job)
            if step1_form.is_valid():
                creating_job=step1_form.save(commit=False)
                creating_job.customer=current_customer
                creating_job.save()
                return redirect(reverse('customer:create_job'))
        elif request.POST.get('step')=='2':
            step2_form=forms.JobCreateStep2Form(request.POST,instance=creating_job)
            if step2_form.is_valid():
                creating_job=step2_form.save()
                return redirect(reverse('customer:create_job'))
        elif request.POST.get('step')=='3':
            step3_form=forms.JobCreateStep3Form(request.POST,instance=creating_job)
            if step3_form.is_valid():
                 creating_job=step3_form.save()
            try:
                    r=requests.get("https://maps.googleapis.com/maps/api/distancematrix/json?origns={}&destinations={}&mode=transit&key={}".format(
                        creating_job.pickup_address,
                        creating_job.delivery_address,
                        settings.GOOGLE_MAP_API_KEY,
                    ))
                        
                    
                    print(r.json()['rows'])
                    distance=r.json()['rows'][0]['elements'][0]['distance']['value']
                    duration=r.json()['rows'][0]['elements'][0]['duration']['value']
                    creating_job.distance=round(distance/1000,2)
                    creating_job.duration=round(duration/60)
                    creating_job.price=creating_job.distance*1
                    create_job_page.save()

            except Exception as e:
                    print(e)
                    messages.error(request,"Unfortunately we don't support shipping at this distance")
    
                    
                    return redirect(reverse('customer:create_job'))
        
        elif request.POST.get('step')=='4':
            if creating_job.price:
                try:
                   payment_intent= stripe.PaymentIntent.create(
                    amount=int(creating_job.price*100),
                    currency='usd',
                    customer=current_customer.stripe_customer_id,
                    payment_method=current_customer.stripe_payment_method_id,
                    off_session=True,
                     confirm=True,
                   )
                   Transaction.objects.create(
                       stripe_payment_intent_id=payment_intent['id'],
                       job=creating_job,
                       amount=creating_job.price,
                   )
                   creating_job.status=Job.PROCESSING_STATUS
                   creating_job.save()
                   return redirect(reverse('customer:home'))
                    
                except stripe.error.CardError as e:
                       err = e.error
  # Error code will be authentication_required if authentication is needed
                       print("Code is: %s" % err.code)
                       payment_intent_id = err.payment_intent['id']
                       payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)

    
    if not creating_job:
        current_step=1
    elif creating_job.delivery_name:
        current_step=4

    elif creating_job.pickup_name:
        current_step=3

    else:
        current_step=2


    return render(request,'customer/create_job.html', {
        "step1_form":step1_form,
        "step2_form":step2_form,
        "step3_form":step3_form,



       "job":creating_job,
       "step":current_step,
       "GOOGLE_MAP_API_KEY":settings.GOOGLE_MAP_API_KEY

      })


@login_required(login_url="/sign-in/?next=/customer/")
def current_jobs_page(request):
    jobs=Job.objects.filter(
        customer=request.user.customer,
        status__in=[
            Job.PROCESSING_STATUS,
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]

    )
    return render(request,'customer/jobs.html',{
        "jobs":jobs
    })

@login_required(login_url="/sign-in/?next=/customer/")
def archived_jobs_page(request):
    jobs=Job.objects.filter(
        customer=request.user.customer,
        status__in=[
            Job.COMPLETED_STATUS,
            Job.CANCELED_STATUS,
        ]

    )
    return render(request,'customer/jobs.html',{
        "jobs":jobs
    })

@login_required(login_url="/sign-in/?next=/customer/")
def job_page(request,job_id):
    job=Job.objects.get(id=job_id)

    if request.method=="POST" and job.status==Job.PROCESSING_STATUS:
        job.status=Job.CANCELED_STATUS
        job.save()
        return redirect(reverse('customer:archived_jobs'))
    return render(request,'customer/job.html',{
        "job":job,
        "GOOGLE_MAP_API_KEY":settings.GOOGLE_MAP_API_KEY,
    })
 

core/templates/customer/base.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% url 'customer:create_job' as create_job_url %}
{% url 'customer:profile' as profile_url %}
{% url 'customer:current_jobs' as current_jobs_url %}
{% url 'customer:archived_jobs' as archived_jobs_url %}
{% url 'customer:payment_method' as payment_method_url %}





<div class="container bg-light mt-4 pt-3 pb-3">
    <div class="row">
        <div class="col-lg-4">
            <div class="text-center">
                <img src="{% if request.user.customer.avatar %}{{ request.user.customer.avatar.url }}{% else %} {% static 'img/download.png' %} {% endif %}"
                    alt="" class="rounded-circle mb-2" width="100" height="100">
                <h4>{{ request.user.get_full_name }}</h4>
                <p class="text-seconday">{{ request.user.email }}</p>
            </div>

            <div class="list-group">
                <a href="{% url 'customer:create_job' %}"
                    class="list-group-item  list-group-item-action {% if request.path == create_job_url %} active {% endif %} ">Create
                    a job</a>
                <a href="{% url 'customer:current_jobs' %}"
                    class="list-group-item  list-group-item-action {% if request.path == current_jobs_url or request.path == archived_jobs_url %} active {% endif %} ">My
                    jobs</a>
                <a href="{% url 'customer:profile' %}"
                    class="list-group-item  list-group-item-action {% if request.path == profile_url %} active {% endif %} ">Profile
                    Information</a>
                <a href="{% url 'customer:payment_method' %}"
                    class="list-group-item  list-group-item-action {% if request.path == payment_method_url %} active {% endif %} ">Payment
                    Details</a>

            </div>

        </div>
        <div class="col-lg-8">
            {% block main %}

            {% endblock %}
        </div>

    </div>
</div>
{% endblock %}

core/templates/customer/job.html
{% extends 'customer/base.html' %}
{% load static %}
{% block head %}


<style>
    .photo {
        object-fit: cover;
    }

    .photo-blank {
        border: 2px dashed #DFDFDF;
        height: 130px;
        width: 140px;
        border-radius: 5px;
        align-items: center;
        display: flex;
        justify-content: center;
        text-align: center;
        padding: 10px;

    }
</style>

<script
    src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAP_API_KEY }}&callback=initMap&libraries=places&v=weekly"
    defer></script>
<script>
    var pickupLat = parseFloat("{{ job.pickup_lat }}");
    var pickupLng = parseFloat("{{ job.pickup_lng }}");
    var deliveryLat = parseFloat("{{ job.delivery_lat }}");
    var deliveryLng = parseFloat("{{ job.delivery_lng }}");


    function initMap() {
        const directionsService = new google.maps.DirectionsService();
        const directionsRenderer = new google.maps.DirectionsRenderer();
        const map = new google.maps.Map(document.getElementById("map"), {
            zoom: 7,
            center: { lat: 41.85, lng: -87.65 },
        });


        directionsRenderer.setMap(map);
        calculateAndDisplayRoute(map, directionsService, directionsRenderer);



    }

    function calculateAndDisplayRoute(map, directionsService, directionsRenderer) {
        directionsService.route(
            {
                origin: new google.maps.LatLng(pickupLat, pickupLng),
                destination: new google.maps.LatLng(deliveryLat, deliveryLng),
                travelMode: google.maps.TravelMode.DRIVING,
            },
            (response, status) => {
                if (status === "OK") {
                    new google.maps.DirectionsRenderer({
                        map: map,
                        direction: response,
                        suppressMarkers: true,
                        polylineOptions: {
                            strokeColor: "#000",
                            strokeWeight: 5,
                            strokeCapacity: 0.8
                        }
                    });
                    var leg = response.route[0].legs[0];
                    new google.maps.Marker({
                        position: leg.start_location,
                        map: map,
                        icon: "{% static 'img/stat.png' %}"
                    });
                    new google.maps.Marker({
                        position: leg.end_location,
                        map: map,
                        icon: "{% static 'img/end.png' %}"
                    });

                    directionsRenderer.setDirections(response);
                } else {
                    window.alert("Directions request failed due to " + status);
                }
            }
        );
    }
</script>

{% endblock %}
{% block main %}
<div class="media mb-4">
    <img src="{{ job.photo.url }}" class="rounded-lg mr-3" width="150" height="150">
    <div class="media-body">
        {% if job.status == 'processing' %}
        <form method="POST" class="float-right">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning">Cancel Job</button>
        </form>
        {% endif %}
        <h4>{{ job.name }}</h4>
        <p class="text-secondary"> {{ job.description }} </p>
        <div class="row">
            <div class="col-lg-3">
                <small class="text-secondary"> CATEGORY</small></br />
                <span><b> {{ job.category.name }}</b></span>
            </div>
            <div class="col-lg-3">
                <small class="text-secondary"> SIZE</small></br />
                <span><b> {{ job.get_size_display }}</b></span>
            </div>
            <div class="col-lg-3">
                <small class="text-secondary"> PRICE</small></br />
                <span><b> {{ job.price }}</b></span>
            </div>
            <div class="col-lg-3">
                <small class="text-secondary"> QUANTITY</small></br />
                <span><b> {{ job.quantity }}</b></span>
            </div>


        </div>

    </div>

</div>

<!--Delivery info-->
<b class="text-secondary"> DELIVERY INFORMATION</b><br />
<div class="card bg-white mt-2 mb-5">
    <div class="card-body p-4">
        <h4 class="mb-3">
            Pickup
        </h4>
        <div class="row">
            <div class="col-lg-4">
                <b>Address</b><br />
                <span> {{ job.pickup_address }}</span>
            </div>
            <div class="col-lg-4">
                <b>{{ job.pickup_name }}</b><br />
                <span> {{ job.pickup_phone }}</span>
            </div>
            <div id="pickup_photo" class="col-lg-4">
                {% if job.pickup_photo %}
                <img src="{{ job.pickup.photo.url }}" class="rounded-lg-photo" width="130" height="130">
                {% else %}
                <div class="photo-blank">Pickup Photo will appear here </div>
                {% endif %}

            </div>

        </div>
        <hr class="my-4" />
        <h4 class="mb-3">
            Delivery
        </h4>

        <div class="row">

            <div class="col-lg-4">
                <b>Address</b><br />
                <span> {{ job.delivery_address }}</span>
            </div>
            <div class="col-lg-4">
                <b>{{ job.delivery_name }}</b><br />
                <span> {{ job.delivery.pickup_phone }}</span>
            </div>
            <div id="delivery_photo" class="col-lg-4">
                {% if job.delivery_photo %}
                <img src="{{ job.delivery.photo.url }}" class="rounded-lg-photo" width="130" height="130">
                {% else %}
                <div class="photo-blank">Delivey Photo will appear here </div>
                {% endif %}

            </div>

        </div>
    </div>

</div>

<div class="d-flex justify-content-between">
    <b class="rext-secondary">TRACK DELIVERY</b>
    <div>
        <span class="badge badge-warning">{{ job.get_status_display }}></span>
    </div>
</div>
<div class="card bg-white mt-2">
    <div class="crad-body p-0">
        <div id="map" style="height: 500px;"> </div>

    </div>

</div>

{% endblock %}

core/templates/customer/jobs.html
{% extends 'customer/base.html' %}

{% block main %}
{% url 'customer:current_jobs' as current_jobs_url %}
{% url 'customer:archived_jobs' as archived_jobs_url %}

<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
        <a class="nav-link{% if request.path == current_jobs_url %} active {% endif %}"
            href="{% url 'customer:current_jobs' %}">Current job</a>
    </li>
    <li class="nav-item">
        <a class="nav-link{% if request.path == archived_jobs_url %} active {% endif %}"
            href="{% url 'customer:archived_jobs' %}">Archived job</a>
    </li>
</ul>

<div class="list-group mt-3">
    {% if jobs %}

    {% for job in jobs %}
    <a href="{% url 'customer:job' job.id %}" class="list-group-item list-group-item-action">
        <div class="media">
            <img src="{{ job.photo.url }}" class="round-lg mr-3" width="100" height="100">
            <div class="media-body">
                <div class="row">
                    <div class="col-lg-9">
                        <h5 class="mb-1">{{ job.name }}</h5>
                        <p>{{ job.description }}</p>
                        <div class="d-felx ">
                            <i class="fas fa-map-marker-alt"></i>
                            <div class="ml-2">
                                <b> {{ job.pickup_name }}</b><br />
                                <small> {{ job.pickup_address }}</small>
                            </div>
                            <div class="d-felx ">
                                <i class="fas fa-flag-checkered"></i>
                                <div class="ml-2">
                                    <b> {{ job.delivery_name }}</b><br />
                                    <small> {{ job.delivery_address }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 text-right d-flex-column justify-content-between">
                            <div><span class="badge badge-warning mb-2">{{ job.get_status_display }} </span></div>
                            <h2 class="mb-1">${{ job.price }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </a>


    {% endfor %}

    {% else %}
    <div class="card">
        <div class="card-body text-center">
            Nothing to show here yet

        </div>
    </div>
    {% endif %}


</div>
{% endblock %}

core/templates/customer/payment_method.html
{% extends 'customer/base.html' %}
{% load bootstrap4 %}
{% block head %}
<script src="https://js.stripe.com/v3/"></script>
<style>
    .StripeElement {
        height: 40px;
        padding: 10px 12px;
        width: 100%;
        color: #32325d;
        background-color: white;
        border: 1px solid #ced4ca;
        border-radius: 4px;
    }

    .StripeElement--focus {
        border-color: #80bdff;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, .25);
    }

    .StripeElement {
        border-color: #fa775a;
    }

    .StripeElement-webkit-autofill {
        background-color: #fefde5 !important;
    }
</style>
{% endblock %}
{% block main %}

{% if not request.user.customer.stripe_payment_method_id %}
<div class="alert alert-danger.alert-dismissible fade show" role="alert">
    Let's add your Credit or Debit card to <strong> Create a job</strong>!
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">$times;</span>

    </button>
</div>
{% endif %}




<b class="text-secondary">Your Credit/Debit Card</b>
<div class="card bg-white mt-2 mb-5">
    <div class="card-body">

        {% if request.user.customer.stripe_payment_method_id %}
        <div id="change-card" class="input-group">
            <input type="text" class="form-control" disabled
                value="***** ***** ****{{ request.user.customer.stripe_card_last4 }}">
            <div class="inpit-group-append">
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Remove</button>
                </form>
            </div>

        </div>


        {% else %}
        <form id="setup-form" data-secret="{{ client_secret }}">
            <div id="card-element"></div>
            <button id="card-button" class="btn btn-warning  mt-3" type="button">
                Save Card
            </button>
        </form>
        </form>
        {% endif %}
    </div>
</div>
{% if not request.user.customer.stripe_payment_method_id %}

<script>
    var stripe = Stripe("{{ STRIPE_API_PUBLIC_KEY }}");
    var elements = stripe.elements();
    var cardElement = elements.create('card');
    cardElement.mount('#card-element');
    var cardholderName = document.getElementById('cardholder-name');
    var cardButton = document.getElementById('card-button');
    var clientSecret = "{{ client_secret }}";
    cardButton.addEventListener('click', function (ev) {
        stripe.confirmCardSetup(
            clientSecret,
            {
                payment_method: {
                    card: cardElement,
                },
            }
        ).then(function (result) {
            if (result.error) {
                toast(result.error.message, 'error');
            } else {
                toast("Payment method is added", 'success');
                window.location.reload();

            }
        });
    });
</script>
{% endif %}

{% endblock %}